// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package identitysqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateAccount = `-- name: ActivateAccount :execrows
UPDATE accounts
SET status = 'active', updated_at = $2
WHERE account_id = $1 AND status = 'pending_verification'
`

type ActivateAccountParams struct {
	AccountID pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ActivateAccount(ctx context.Context, arg ActivateAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateAccount, arg.AccountID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeVerificationToken = `-- name: ConsumeVerificationToken :execrows
UPDATE verification_tokens
SET consumed_at = $2
WHERE token_id = $1 AND consumed_at IS NULL AND revoked_at IS NULL
`

type ConsumeVerificationTokenParams struct {
	TokenID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationToken, arg.TokenID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (email_display, email_normalized, password_hash, status, created_at, updated_at)
VALUES ($1, $2, $3, 'pending_verification', $4, $4)
ON CONFLICT (email_normalized) DO NOTHING
RETURNING account_id
`

type CreateAccountParams struct {
	EmailDisplay    string
	EmailNormalized string
	PasswordHash    string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.EmailDisplay,
		arg.EmailNormalized,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const currentVerificationGeneration = `-- name: CurrentVerificationGeneration :one
SELECT COALESCE(MAX(generation), 0)::bigint
FROM verification_tokens
WHERE account_id = $1 AND purpose = $2
`

type CurrentVerificationGenerationParams struct {
	AccountID pgtype.UUID
	Purpose   string
}

func (q *Queries) CurrentVerificationGeneration(ctx context.Context, arg CurrentVerificationGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, currentVerificationGeneration, arg.AccountID, arg.Purpose)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findAccountByEmailForUpdate = `-- name: FindAccountByEmailForUpdate :one
SELECT account_id, email_display, status
FROM accounts
WHERE email_normalized = $1
FOR UPDATE
`

type FindAccountByEmailForUpdateRow struct {
	AccountID    pgtype.UUID
	EmailDisplay string
	Status       string
}

func (q *Queries) FindAccountByEmailForUpdate(ctx context.Context, emailNormalized string) (FindAccountByEmailForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findAccountByEmailForUpdate, emailNormalized)
	var i FindAccountByEmailForUpdateRow
	err := row.Scan(&i.AccountID, &i.EmailDisplay, &i.Status)
	return i, err
}

const findVerificationTokenForUpdate = `-- name: FindVerificationTokenForUpdate :one
SELECT token_id, account_id, purpose, generation, expires_at, consumed_at, revoked_at
FROM verification_tokens
WHERE token_digest = $1
FOR UPDATE
`

type FindVerificationTokenForUpdateRow struct {
	TokenID    pgtype.UUID
	AccountID  pgtype.UUID
	Purpose    string
	Generation int64
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) FindVerificationTokenForUpdate(ctx context.Context, tokenDigest []byte) (FindVerificationTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findVerificationTokenForUpdate, tokenDigest)
	var i FindVerificationTokenForUpdateRow
	err := row.Scan(
		&i.TokenID,
		&i.AccountID,
		&i.Purpose,
		&i.Generation,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertIdentitySecurityEvent = `-- name: InsertIdentitySecurityEvent :exec
INSERT INTO identity_security_events (account_id, event_type, occurred_at, payload)
VALUES ($1, $2, $3, $4)
`

type InsertIdentitySecurityEventParams struct {
	AccountID  pgtype.UUID
	EventType  string
	OccurredAt pgtype.Timestamptz
	Payload    []byte
}

func (q *Queries) InsertIdentitySecurityEvent(ctx context.Context, arg InsertIdentitySecurityEventParams) error {
	_, err := q.db.Exec(ctx, insertIdentitySecurityEvent,
		arg.AccountID,
		arg.EventType,
		arg.OccurredAt,
		arg.Payload,
	)
	return err
}

const insertVerificationToken = `-- name: InsertVerificationToken :exec
INSERT INTO verification_tokens (account_id, purpose, generation, token_digest, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertVerificationTokenParams struct {
	AccountID   pgtype.UUID
	Purpose     string
	Generation  int64
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertVerificationToken,
		arg.AccountID,
		arg.Purpose,
		arg.Generation,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const lockVerificationAccountByDigest = `-- name: LockVerificationAccountByDigest :one
SELECT accounts.account_id
FROM accounts
JOIN verification_tokens USING (account_id)
WHERE verification_tokens.token_digest = $1
FOR UPDATE OF accounts
`

func (q *Queries) LockVerificationAccountByDigest(ctx context.Context, tokenDigest []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockVerificationAccountByDigest, tokenDigest)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const nextVerificationGeneration = `-- name: NextVerificationGeneration :one
SELECT COALESCE(MAX(generation), 0)::bigint + 1
FROM verification_tokens
WHERE account_id = $1 AND purpose = $2
`

type NextVerificationGenerationParams struct {
	AccountID pgtype.UUID
	Purpose   string
}

func (q *Queries) NextVerificationGeneration(ctx context.Context, arg NextVerificationGenerationParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextVerificationGeneration, arg.AccountID, arg.Purpose)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const revokeVerificationTokens = `-- name: RevokeVerificationTokens :exec
UPDATE verification_tokens
SET revoked_at = $3
WHERE account_id = $1 AND purpose = $2 AND consumed_at IS NULL AND revoked_at IS NULL
`

type RevokeVerificationTokensParams struct {
	AccountID pgtype.UUID
	Purpose   string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeVerificationTokens(ctx context.Context, arg RevokeVerificationTokensParams) error {
	_, err := q.db.Exec(ctx, revokeVerificationTokens, arg.AccountID, arg.Purpose, arg.RevokedAt)
	return err
}
