// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitysqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID       pgtype.UUID
	EmailDisplay    string
	EmailNormalized string
	PasswordHash    string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type IdentitySecurityEvent struct {
	EventID    int64
	AccountID  pgtype.UUID
	EventType  string
	OccurredAt pgtype.Timestamptz
	Payload    []byte
}

type VerificationToken struct {
	TokenID     pgtype.UUID
	AccountID   pgtype.UUID
	Purpose     string
	Generation  int64
	TokenDigest []byte
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
